import Head from 'next/head'
import Link from 'next/link'
import pg from '../../db'

import Students from '../../components/students'
import { useState } from 'react'

export async function getStaticProps() {
	const students = await pg.query('select * from students')

	return {
		props: {
			students: students.rows,
		},
	}
}

export default function Home(props) {
	const [students, setStudents] = useState(props.students)

	return (
		<>
			<Head>
				<title>School</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className={'p-20'}>
				<Link href='/'>Home</Link>
				<Students students={students} setStudents={setStudents} />
			</div>
		</>
	)
}
