import Head from 'next/head'

import pg from '../db'
import Students from '../components/students'
import { useState } from 'react'

export async function getStaticProps() {
	const teachers = await pg.query('select * from teachers')
	const students = await pg.query(
		"select id, first_name || ' ' || last_name name, age, grade from students",
	)

	return {
		props: {
			teachers: teachers.rows,
			students: students.rows,
		},
	}
}

export default function Home(props) {
	const [students, setStudents] = useState(props.students)
	const [teachers, setTeachers] = useState(props.teachers)

	return (
		<div className={'p-10'}>
			<Head>
				<title>School</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<h1 className={'text-6xl font-bold'}>School</h1>

			<Students students={students} setStudents={setStudents} />
		</div>
	)
}
