import Head from 'next/head'

import pg from '../db'
import Students from '../components/students'
import { useState } from 'react'

export async function getStaticProps() {
	const teachers = await pg.query('select * from teachers')
	const students = await pg.query(
		"select id, first_name || ' ' || last_name name, age, grade from students",
	)

	return {
		props: {
			teachers: teachers.rows,
			students: students.rows,
		},
	}
}

export default function Home(props) {
	const [students, setStudents] = useState(props.students)
	const [teachers, setTeachers] = useState(props.teachers)

	return (
		<div className={'p-6'}>
			<Head>
				<title>School</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<h1 className={'text-6xl font-bold p-6'}>School</h1>

			<h2 className='font-bold'>All Teachers</h2>
			<ul className='flex bg-green-200'>
				{teachers.map(teacher => (
					<li key={teacher.id} className='p-6'>
						{teacher.last_name}
					</li>
				))}
			</ul>

			<Students students={students} setStudents={setStudents} />
		</div>
	)
}
