import Head from 'next/head'
import Link from 'next/link'

export async function getStaticProps() {
	return {
		props: {},
	}
}

export default function Home(props) {
	return (
		<>
			<Head>
				<title>School</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className={'p-20'}>
				<Link href='/students'>Students</Link>
				<h1 className={'text-6xl font-bold'}>School</h1>
			</div>
		</>
	)
}
